### ISSUE TITLE
Issues applying patch (.ctp file)

### ISSUE THREAD

**Issue by whickus70** [jimzrt/ChronoMod#1]
Hello,

Previous to the March 2022 update to Chrono Trigger I had been using the "Allow Crono to be named Chrono" mod (chrono_name.ctp file) found here - http://www.remurin.com/ChronoMods/.

After updating Chrono Trigger to v2.0.0.1, that mod was no longer applied, which is to be expected as the update overwrote the resources.bin file. I attempted to reapply the chrono_name.ctp patch using your ChronoMod. However, upon starting the game and choosing New Game in order to try naming him Chrono, the game locked on a black screen. Using CT_Explore v1.4 to reapply the same chrono_name.ctp patch worked with no issues.

**Comment by jimzrt** [comment]
Thanks for reporting.
I did a clean update of dependencies and rebuild.
After applying the same patch you did, everything worked as expected, so please try again.

Closing for now, will reopen if the problem happens again.
